services:
  web:
    build: .
    container_name: aria-chatbot
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - ollama
      - db
    command: uv run python manage.py runserver 0.0.0.0:8000

  ollama:
    image: ollama/ollama:latest
    container_name: aria-ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama

  db:
    image: postgres:18
    container_name: aria-postgres
    environment:
      POSTGRES_DB: aria_chatbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  ollama_data:
  postgres_data: