services:
  web:
    build: .
    container_name: aria_chatbot_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - ollama
    volumes:
      - .:/app

  db:
    image: postgres:18
    container_name: aria_chatbot_db
    environment:
      POSTGRES_DB: aria_chatbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    container_name: aria_chatbot_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  postgres_data:
  ollama_data: