# Generated by Django 6.1.1 on 2026-09-29 12:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
